### ISSUE TITLE
It is a emulator for linux or just a client tool for linux?

### ISSUE THREAD

**Issue by alexwenbj** [bobmcdouble3/webemulator#1]
Hi,It seems this is a funny tool for educator,I wonder is it a emulator(it means we do not need the Linux server) or it is just a web-based terminal of Linux (It means we need the Linux server)?
Thanks!

**Comment by bobmcdouble3** [comment]
Hey! Funny you found this today. This is actually a fork of jor1k (https://github.com/s-macke/jor1k/). My version is meant to be used as a mobile webapp. This will emulate a linux environment. You do not need a server for this.

**Comment by alexwenbj** [comment]
Great!Thank you!
